package corpus

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

// BooksManifest is manifests/books.yaml, the record of which PDFs the corpus
// was built from.
type BooksManifest struct {
	Books []Book `yaml:"books"`
}

// Book is one source volume.
type Book struct {
	ID         string   `yaml:"id"`
	Book       string   `yaml:"book"`
	Title      string   `yaml:"title"`
	Edition    string   `yaml:"edition"`
	Chapters   []string `yaml:"chapters"`
	PDF        string   `yaml:"pdf"`
	PDFSHA256  string   `yaml:"pdf_sha256"`
	PDFBytes   int64    `yaml:"pdf_bytes"`
	Pages      int      `yaml:"pages"`
	Nature     string   `yaml:"nature"`
	Producer   string   `yaml:"producer,omitempty"`
	Scan       *Scan    `yaml:"scan,omitempty"`
	Extraction string   `yaml:"extraction"`
	PageWidth  float64  `yaml:"page_width_pt,omitempty"`
	PageHeight float64  `yaml:"page_height_pt,omitempty"`
	// Grammar is how the volume prints its page number, "head-label" or
	// "foot-number", and Pagination is what that number counts, "per-chapter"
	// or "continuous". Both are filled in by pagemap build, which detects them
	// and records what it found rather than asking anyone to remember.
	Grammar    string `yaml:"grammar,omitempty"`
	Pagination string `yaml:"pagination,omitempty"`
}

// Scan describes the page images of a scanned volume.
type Scan struct {
	Format string `yaml:"format"`
	Width  int    `yaml:"width"`
	Height int    `yaml:"height"`
	DPI    int    `yaml:"dpi"`
	BPC    int    `yaml:"bpc"`
	Color  string `yaml:"color"`
}

// LoadBooks reads manifests/books.yaml under root. A missing file is not an
// error, it is an empty manifest, so the first books add works on a fresh repo.
func LoadBooks(root string) (*BooksManifest, error) {
	path := BooksPath(root)
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &BooksManifest{}, nil
	}
	if err != nil {
		return nil, err
	}
	var m BooksManifest
	if err := yaml.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &m, nil
}

// Save writes the manifest back, sorted by chapter order so the file is stable
// across runs and diffs stay readable.
func (m *BooksManifest) Save(root string) error {
	sort.SliceStable(m.Books, func(i, j int) bool {
		return m.Books[i].order() < m.Books[j].order()
	})
	var buf []byte
	enc, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	buf = append([]byte("# Generated by bourbaki books add. Edit the PDFs, not this file.\n"), enc...)
	path := BooksPath(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, buf, 0o644)
}

// order sorts volumes by their first chapter, so I-III comes before IV-VII
// comes before VIII rather than sorting by id.
func (b Book) order() int {
	if len(b.Chapters) == 0 {
		return 1 << 30
	}
	n, err := RomanOrder(b.Chapters[0])
	if err != nil {
		return 1 << 30
	}
	return n
}

// Get returns the book with the given id.
func (m *BooksManifest) Get(id string) (*Book, bool) {
	for i := range m.Books {
		if m.Books[i].ID == id {
			return &m.Books[i], true
		}
	}
	return nil, false
}

// Upsert replaces the book with the same id, or appends it.
func (m *BooksManifest) Upsert(b Book) {
	for i := range m.Books {
		if m.Books[i].ID == b.ID {
			m.Books[i] = b
			return
		}
	}
	m.Books = append(m.Books, b)
}

// Pages is the total page count across all volumes.
func (m *BooksManifest) Pages() int {
	n := 0
	for _, b := range m.Books {
		n += b.Pages
	}
	return n
}

// BooksPath is where the manifest lives inside a corpus checkout.
func BooksPath(root string) string { return filepath.Join(root, "manifests", "books.yaml") }

// Root resolves the corpus checkout from BOURBAKI_CORPUS, falling back to the
// working directory.
func Root() (string, error) {
	if r := os.Getenv("BOURBAKI_CORPUS"); r != "" {
		return filepath.Abs(r)
	}
	return os.Getwd()
}
