package corpus

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// SectionsManifest is manifests/sections.yaml, one line of accounting for every
// file assembly wrote: which PDF pages went into it, how much came out, and
// what the bytes hash to.
//
// It is written for the reader rather than for the program, which is why it
// holds counts and not content. Assembly needs nothing from it, since it works
// from the pages and the table of contents. What it answers is the question
// nobody can answer by looking at a directory of 26 Markdown files: whether
// every page of the volume ended up in exactly one of them, and whether the
// statements and exercises the corpus claims are the ones the book prints.
type SectionsManifest struct {
	Books []BookSections `yaml:"books"`
}

// BookSections is one volume.
type BookSections struct {
	ID string `yaml:"id"`
	// Introduction is the Book's own introduction, where the volume has one. It
	// is beside the chapters rather than in them because it is in no chapter,
	// and it is accounted for like any other file: a part of the book that is
	// written and not counted is a part nobody notices is missing.
	Introduction *SectionRecord    `yaml:"introduction,omitempty"`
	Chapters     []ChapterSections `yaml:"chapters"`
}

// ChapterSections is one chapter.
type ChapterSections struct {
	Chapter  string          `yaml:"chapter"`
	Title    string          `yaml:"title"`
	Sections []SectionRecord `yaml:"sections"`
}

// SectionRecord is one assembled file.
type SectionRecord struct {
	// Kind is front, section, appendix or historical. The chapter's opening
	// pages and its historical note are files like any other and are counted
	// like any other, but neither is a §, so neither has a number.
	Kind          string `yaml:"kind"`
	Section       int    `yaml:"section,omitempty"`
	Title         string `yaml:"title,omitempty"`
	Path          string `yaml:"path"`
	Label         string `yaml:"label,omitempty"`
	FirstPDFPage  int    `yaml:"first_pdf_page"`
	LastPDFPage   int    `yaml:"last_pdf_page"`
	BookPages     string `yaml:"book_pages,omitempty"`
	Subsections   int    `yaml:"subsections"`
	Statements    int    `yaml:"statements"`
	Exercises     int    `yaml:"exercises"`
	Extraction    string `yaml:"extraction"`
	ContentSHA256 string `yaml:"content_sha256"`
}

// Section kinds.
const (
	KindFront = "front"
	// KindIntroduction is the Book's own introduction, which stands before
	// chapter I and belongs to no chapter. It is the one kind whose file is not
	// in a chapter directory. See Book.Introduction.
	KindIntroduction = "introduction"
	KindSection      = "section"
	KindAppendix     = "appendix"
	KindHistorical   = "historical"
)

// LoadSections reads manifests/sections.yaml. A missing file is an empty
// manifest, so the first assemble works on a fresh repo.
func LoadSections(root string) (*SectionsManifest, error) {
	path := SectionsPath(root)
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &SectionsManifest{}, nil
	}
	if err != nil {
		return nil, err
	}
	var m SectionsManifest
	if err := yaml.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &m, nil
}

// Upsert replaces a volume's record, or appends it, leaving the order of the
// other volumes alone.
func (m *SectionsManifest) Upsert(b BookSections) {
	for i := range m.Books {
		if m.Books[i].ID == b.ID {
			m.Books[i] = b
			return
		}
	}
	m.Books = append(m.Books, b)
}

// Bytes renders the manifest.
func (m *SectionsManifest) Bytes() ([]byte, error) {
	enc, err := yaml.Marshal(m)
	if err != nil {
		return nil, err
	}
	return append([]byte("# Generated by bourbaki assemble. Do not edit.\n"), enc...), nil
}

// Save writes the manifest back.
func (m *SectionsManifest) Save(root string) error {
	b, err := m.Bytes()
	if err != nil {
		return err
	}
	path := SectionsPath(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

// SectionsPath is where the manifest lives inside a corpus checkout.
func SectionsPath(root string) string {
	return filepath.Join(root, "manifests", "sections.yaml")
}
