package corpus

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSectionsRoundTrip(t *testing.T) {
	root := t.TempDir()
	m, err := LoadSections(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Books) != 0 {
		t.Fatalf("a fresh repo should read as an empty manifest, got %d volumes", len(m.Books))
	}
	m.Upsert(BookSections{ID: "alg-viii", Chapters: []ChapterSections{{
		Chapter: "VIII", Title: "Semisimple Modules and Rings",
		Sections: []SectionRecord{{
			Kind: KindSection, Section: 1, Title: "Artinian Modules and Noetherian Modules",
			Path:  "content/en/alg/VIII/01_s1_artinian_modules_and_noetherian_modules.md",
			Label: "alg-viii-s1", FirstPDFPage: 18, LastPDFPage: 40, BookPages: "A VIII.1-A VIII.23",
			Subsections: 8, Statements: 30, Exercises: 28, Extraction: "native",
			ContentSHA256: "fbbf15793d11141a9572c80128ac4905b93983d34a3d90c2e576b864e845de20",
		}},
	}}})
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(SectionsPath(root))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# Generated by bourbaki assemble.") {
		t.Errorf("the manifest carries no generated line: %q", first(string(b), 40))
	}
	back, err := LoadSections(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(back.Books) != 1 || len(back.Books[0].Chapters) != 1 || len(back.Books[0].Chapters[0].Sections) != 1 {
		t.Fatalf("read back %+v", back)
	}
	if got, want := back.Books[0].Chapters[0].Sections[0], m.Books[0].Chapters[0].Sections[0]; got != want {
		t.Errorf("read back %+v, want %+v", got, want)
	}
}

// A second run of the same volume replaces its record rather than adding
// another, and leaves the other volumes where they were.
func TestSectionsUpsert(t *testing.T) {
	m := &SectionsManifest{}
	m.Upsert(BookSections{ID: "alg-i-iii"})
	m.Upsert(BookSections{ID: "alg-viii"})
	m.Upsert(BookSections{ID: "alg-i-iii", Chapters: []ChapterSections{{Chapter: "I"}}})
	if len(m.Books) != 2 {
		t.Fatalf("got %d volumes, want 2", len(m.Books))
	}
	if m.Books[0].ID != "alg-i-iii" || len(m.Books[0].Chapters) != 1 {
		t.Errorf("the first volume is %+v", m.Books[0])
	}
	if m.Books[1].ID != "alg-viii" {
		t.Errorf("the second volume is %+v", m.Books[1])
	}
}

// The chapter's opening pages and its historical note are files like any other
// and are named for what they are, because neither is a § and neither has a
// number to be named for. The appendices sort after the sections and before the
// note.
func TestSectionPathNames(t *testing.T) {
	root := "/corpus"
	cases := []struct {
		meta SectionFrontMatter
		name string
	}{
		{SectionFrontMatter{Book: "alg", Chapter: "VIII", Kind: KindFront, SectionTitle: "Semisimple Modules and Rings"},
			"00_frontmatter.md"},
		{SectionFrontMatter{Book: "alg", Chapter: "VIII", Section: 1, SectionTitle: "Artinian Modules and Noetherian Modules"},
			"01_s1_artinian_modules_and_noetherian_modules.md"},
		{SectionFrontMatter{Book: "alg", Chapter: "VIII", Section: 21, SectionTitle: "Linear Representations of Finite Groups"},
			"21_s21_linear_representations_of_finite_groups.md"},
		{SectionFrontMatter{Book: "alg", Chapter: "VIII", Section: 2, Appendix: true, SectionTitle: "Determinants over a Field"},
			"A2_a2_determinants_over_a_field.md"},
		{SectionFrontMatter{Book: "alg", Chapter: "II", Appendix: true, SectionTitle: "Alternative Algebras"},
			"A_a_alternative_algebras.md"},
		{SectionFrontMatter{Book: "alg", Chapter: "I", Kind: KindHistorical, SectionTitle: "Historical Note"},
			"historical_note.md"},
	}
	var names []string
	for _, c := range cases {
		got := SectionPath(root, "en", c.meta)
		want := filepath.Join(root, "content", "en", c.meta.Book, c.meta.Chapter, c.name)
		if got != want {
			t.Errorf("SectionPath = %q, want %q", got, want)
		}
		names = append(names, c.name)
	}
	order := []string{names[0], names[1], names[2], names[3], names[5]}
	for i := 1; i < len(order); i++ {
		if order[i-1] >= order[i] {
			t.Errorf("%q does not sort before %q", order[i-1], order[i])
		}
	}
}

func first(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
