package corpus

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// TOCManifest is manifests/toc.yaml, the chapter, § and no. tree of every
// volume, with both numberings on every entry. It is the plan extraction works
// to: it says which PDF pages hold § 3 of chapter V without anybody counting.
type TOCManifest struct {
	Books []BookTOC `yaml:"books"`
}

// BookTOC is one volume's contents.
type BookTOC struct {
	ID       string    `yaml:"id"`
	Grammar  string    `yaml:"grammar"`
	Chapters []Chapter `yaml:"chapters"`
}

// LoadTOC reads manifests/toc.yaml. A missing file is an empty manifest, so the
// first toc build works on a fresh repo.
func LoadTOC(root string) (*TOCManifest, error) {
	path := TOCPath(root)
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &TOCManifest{}, nil
	}
	if err != nil {
		return nil, err
	}
	var m TOCManifest
	if err := yaml.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &m, nil
}

// Save writes the manifest back.
func (m *TOCManifest) Save(root string) error {
	enc, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	buf := append([]byte("# Generated by bourbaki toc build. Do not edit.\n"), enc...)
	path := TOCPath(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, buf, 0o644)
}

// Upsert replaces a volume's contents, or appends it, keeping the order of
// manifests/books.yaml stable by leaving existing entries where they are.
func (m *TOCManifest) Upsert(b BookTOC) {
	for i := range m.Books {
		if m.Books[i].ID == b.ID {
			m.Books[i] = b
			return
		}
	}
	m.Books = append(m.Books, b)
}

// Get returns a volume's contents.
func (m *TOCManifest) Get(id string) (*BookTOC, bool) {
	for i := range m.Books {
		if m.Books[i].ID == id {
			return &m.Books[i], true
		}
	}
	return nil, false
}

// Chapter finds a chapter by numeral across every volume, since a chapter
// belongs to the Book Algebra rather than to the volume it happens to be bound
// in, and callers think in chapters.
func (m *TOCManifest) Chapter(numeral string) (*Chapter, bool) {
	for i := range m.Books {
		for j := range m.Books[i].Chapters {
			if m.Books[i].Chapters[j].Numeral == numeral {
				return &m.Books[i].Chapters[j], true
			}
		}
	}
	return nil, false
}

// TOCPath is where the manifest lives inside a corpus checkout.
func TOCPath(root string) string { return filepath.Join(root, "manifests", "toc.yaml") }
