package corpus

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

// TOCManifest is manifests/toc/, the chapter, § and no. tree of every volume,
// with both numberings on every entry. It is the plan extraction works to: it
// says which PDF pages hold § 3 of chapter V without anybody counting.
//
// It is one file to a volume. It was one file to the corpus until the tree ran
// to 587 KB, over the size H03 holds a tracked file to, and the size of the
// whole tree is a linear function of how much of the Éléments has been read: a
// volume arrives in it as its contents page is read, twenty-eight of the forty
// are in, and a single file would have gone on growing. Per volume it does not
// grow, and the largest of them is under 60 KB.
type TOCManifest struct {
	Books []BookTOC `yaml:"books"`
}

// BookTOC is one volume's contents, and one file under manifests/toc/.
type BookTOC struct {
	ID       string    `yaml:"id"`
	Grammar  string    `yaml:"grammar"`
	Chapters []Chapter `yaml:"chapters"`
}

// LoadTOC reads manifests/toc/. A missing directory is an empty manifest, so
// the first toc build works on a fresh repo.
//
// The volumes come back in the order the file names sort, which is the order
// their ids sort, and not the order of manifests/books.yaml. Nothing reads the
// manifest in order, and a stable order is what keeps a rebuild that changed
// one volume from rewriting the rest.
func LoadTOC(root string) (*TOCManifest, error) {
	ents, err := os.ReadDir(TOCDir(root))
	if os.IsNotExist(err) {
		return &TOCManifest{}, nil
	}
	if err != nil {
		return nil, err
	}
	m := &TOCManifest{}
	for _, e := range ents {
		if e.IsDir() || filepath.Ext(e.Name()) != ".yaml" {
			continue
		}
		path := filepath.Join(TOCDir(root), e.Name())
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var bt BookTOC
		if err := yaml.Unmarshal(b, &bt); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		m.Books = append(m.Books, bt)
	}
	sort.Slice(m.Books, func(i, j int) bool { return m.Books[i].ID < m.Books[j].ID })
	return m, nil
}

// Save writes the manifest back, one file to a volume.
//
// A volume that is no longer in the manifest has its file removed, because the
// directory is the manifest and a file left behind in it would be read back on
// the next load as a volume that is still there.
func (m *TOCManifest) Save(root string) error {
	dir := TOCDir(root)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	keep := map[string]bool{}
	for _, b := range m.Books {
		enc, err := yaml.Marshal(b)
		if err != nil {
			return err
		}
		buf := append([]byte("# Generated by bourbaki toc build. Do not edit.\n"), enc...)
		name := b.ID + ".yaml"
		keep[name] = true
		if err := writeIfChanged(filepath.Join(dir, name), buf); err != nil {
			return err
		}
	}
	ents, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range ents {
		if e.IsDir() || filepath.Ext(e.Name()) != ".yaml" || keep[e.Name()] {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

// writeIfChanged leaves a file whose bytes are already what they should be
// alone, so that a build of one volume touches one file.
func writeIfChanged(path string, buf []byte) error {
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, buf) {
		return nil
	}
	return os.WriteFile(path, buf, 0o644)
}

// Upsert replaces a volume's contents, or appends it, keeping the order of
// manifests/books.yaml stable by leaving existing entries where they are.
func (m *TOCManifest) Upsert(b BookTOC) {
	for i := range m.Books {
		if m.Books[i].ID == b.ID {
			m.Books[i] = b
			return
		}
	}
	m.Books = append(m.Books, b)
}

// Get returns a volume's contents.
func (m *TOCManifest) Get(id string) (*BookTOC, bool) {
	for i := range m.Books {
		if m.Books[i].ID == id {
			return &m.Books[i], true
		}
	}
	return nil, false
}

// Chapter finds a chapter by numeral across every volume, since a chapter
// belongs to the Book Algebra rather than to the volume it happens to be bound
// in, and callers think in chapters.
func (m *TOCManifest) Chapter(numeral string) (*Chapter, bool) {
	for i := range m.Books {
		for j := range m.Books[i].Chapters {
			if m.Books[i].Chapters[j].Numeral == numeral {
				return &m.Books[i].Chapters[j], true
			}
		}
	}
	return nil, false
}

// TOCDir is where the manifest lives inside a corpus checkout.
func TOCDir(root string) string { return filepath.Join(root, "manifests", "toc") }

// TOCPath is the file one volume's contents is written to.
func TOCPath(root, id string) string { return filepath.Join(TOCDir(root), id+".yaml") }
