package corpus

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestTOCRoundTrip(t *testing.T) {
	root := t.TempDir()
	m, err := LoadTOC(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Books) != 0 {
		t.Fatalf("a fresh repo should read as an empty manifest, got %d volumes", len(m.Books))
	}
	m.Upsert(BookTOC{ID: "alg-viii", Grammar: "chapter", Chapters: []Chapter{{
		Book: "alg-viii", Numeral: "VIII", Title: "SEMISIMPLE MODULES AND RINGS", Page: 1,
		Sections: []Section{{Number: 1, Title: "Artinian modules and Noetherian modules", Page: 1}},
	}}})
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(TOCPath(root, "alg-viii"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# Generated by bourbaki toc build.") {
		t.Errorf("the manifest carries no generated line: %q", first(string(b), 40))
	}
	back, err := LoadTOC(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(back.Books) != 1 || back.Books[0].ID != "alg-viii" {
		t.Fatalf("the volume did not come back, got %+v", back.Books)
	}
	if len(back.Books[0].Chapters) != 1 || back.Books[0].Chapters[0].Numeral != "VIII" {
		t.Errorf("the chapter did not come back, got %+v", back.Books[0].Chapters)
	}
	if back.Books[0].Grammar != "chapter" {
		t.Errorf("grammar = %q, want chapter", back.Books[0].Grammar)
	}
}

// The manifest is a directory, so what is in the directory is what the manifest
// says. A volume that has gone has to have its file go with it, or the next
// load reads a volume nobody put there.
func TestTOCDropsAVolumeThatIsGone(t *testing.T) {
	root := t.TempDir()
	m := &TOCManifest{}
	m.Upsert(BookTOC{ID: "alg-viii"})
	m.Upsert(BookTOC{ID: "top-i-iv"})
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	m.Books = m.Books[:1]
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(TOCPath(root, "top-i-iv")); !os.IsNotExist(err) {
		t.Errorf("the file of the volume that went is still there, err = %v", err)
	}
	back, err := LoadTOC(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(back.Books) != 1 {
		t.Errorf("read back %d volumes, want 1", len(back.Books))
	}
}

// A build of one volume writes one volume, and the point of splitting the
// manifest is that it no longer rewrites the other twenty-seven. Save is given
// every volume it has and only the one whose bytes moved is touched.
func TestTOCLeavesTheOtherVolumesAlone(t *testing.T) {
	root := t.TempDir()
	m := &TOCManifest{}
	m.Upsert(BookTOC{ID: "alg-viii", Grammar: "chapter"})
	m.Upsert(BookTOC{ID: "top-i-iv", Grammar: "chapter"})
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	st, err := os.Stat(TOCPath(root, "top-i-iv"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chtimes(TOCPath(root, "top-i-iv"), st.ModTime(), st.ModTime()); err != nil {
		t.Fatal(err)
	}
	m.Upsert(BookTOC{ID: "alg-viii", Grammar: "book"})
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	now, err := os.Stat(TOCPath(root, "top-i-iv"))
	if err != nil {
		t.Fatal(err)
	}
	if !now.ModTime().Equal(st.ModTime()) {
		t.Errorf("the volume that did not change was written again, %v then %v", st.ModTime(), now.ModTime())
	}
	back, err := LoadTOC(root)
	if err != nil {
		t.Fatal(err)
	}
	if bt, _ := back.Get("alg-viii"); bt.Grammar != "book" {
		t.Errorf("the volume that did change reads %q, want book", bt.Grammar)
	}
}

// Anything in the directory that is not a volume file is not a volume. A gaps
// file or an editor's leftover sitting beside them would otherwise come back as
// a volume with no id at all.
func TestTOCReadsOnlyYAML(t *testing.T) {
	root := t.TempDir()
	m := &TOCManifest{}
	m.Upsert(BookTOC{ID: "alg-viii"})
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(TOCDir(root), "notes.txt"), []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}
	back, err := LoadTOC(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(back.Books) != 1 {
		t.Errorf("read back %d volumes, want 1", len(back.Books))
	}
	if _, err := os.Stat(filepath.Join(TOCDir(root), "notes.txt")); err != nil {
		t.Errorf("a file that is not a volume was removed: %v", err)
	}
}
