package glossary

import (
	"strings"
	"unicode"
)

// What a printing sets upright inside a formula that is not prose.
//
// SameMath has to decide, for every run inside a \text, whether the run is
// prose the translation may rewrite or a name it has to copy. It used to decide
// that by asking whether the run held a word of the english list, and read a run
// the list did not know as a name. That is the wrong way round, and it cost
// files.
//
// The list is a hundred or so words chosen for a different question, which is
// whether a piece of writing is still in English, and it is deliberately missing
// every word Vietnamese spells the same way: in, to, an, do, so, may, can. Read
// as a test of prose it then calls \text{in} a name and refuses any answer that
// translated it, and \text{in} appears 37 times in the English corpus. It also
// calls a name of everything the list simply has no reason to carry: vertices,
// an integer, terms, factors, finite, scalars, compact, with respect to, whence,
// rational integers. Reading every \text run in content/en, 338 of 1455 hold no
// word of the list and 102 of those are distinct, and the great majority of them
// are ordinary prose.
//
// Ado's theorem is what it cost. § 7 of Lie chapter I sets a whole paragraph of
// its proof inside one display, and among the runs are "be the kernel of", which
// the list knows, and "generated by", which it does not. So the answer had to
// translate the first and copy the second, in the same sentence of the same
// formula. No model does that. The chunk was asked three times and refused three
// times and took the file with it.
//
// So the question is asked the other way round now. The names are a short list
// and they can be written down, because a name set upright inside a formula is
// an abbreviation of a word the printing has decided not to spell: Tr, res, sym,
// dis, mod, resp., Card, tr. deg, Arc sin. Everything else is prose. What that
// changes is only what a translation is permitted to rewrite, never what it is
// required to rewrite: a run has to be translated when the english list knows a
// word of it, which is the rule L12 and UntranslatedMathProse read and which is
// untouched. So nothing on disk goes stale, and the runs this frees up are runs
// a model may translate or may copy and either answer is accepted.
var mathNames = map[string]bool{}

func init() {
	// The operator names and abbreviations the Elements sets upright, plus the
	// roman numerals, which name a chapter and are not words. A run of one
	// letter is a name whatever it is, and is not on the list.
	for _, w := range strings.Fields(`tr res sym dis mod resp card deg arc sin cos tan cot sec
sinh cosh tanh log exp ker im coker id sup inf max min lim colim det pr hom end aut gl sl pgl psl
rad supp diam vol div grad tors ann codim gr ie lei ia ib
ii iii iv vi vii viii ix xi xii xiii xiv xv xvi xvii xviii xix xx`) {
		mathNames[w] = true
	}
}

// IsMathName says whether a run of a \text is a name the printing sets upright
// rather than prose in the language of the printing.
//
// A run is a name when every word in it is one. A word of one letter is a name,
// because a single letter inside a formula is a symbol however it was typed, and
// a run with no letters at all is a name for the same reason: a bracket, a
// quotation mark, a dash or a number has no language to be in.
//
// The words are cut on anything that is not a letter, so "i.e.," is i and e,
// "tr . deg" is tr and deg, and "(resp." is resp. That is coarser than reading
// the punctuation and it is what the punctuation deserves here, since the
// scanners set "tr . deg" and "tr. deg" for the same three characters and both
// have to come out the same way.
func IsMathName(run string) bool {
	for _, w := range strings.FieldsFunc(strings.ToLower(run), func(r rune) bool {
		return !unicode.IsLetter(r)
	}) {
		if len([]rune(w)) == 1 || mathNames[w] {
			continue
		}
		return false
	}
	return true
}
