package refs

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tamnd/bourbaki-solver/corpus"
)

// The reports the graph is worth reading through. They go in the corpus so that
// a reader who has never run the tool can still see what the chapter leans on,
// what nothing leans on, and where the corpus is short of what it cites.
const (
	ReportMostCited   = "most-cited.md"
	ReportOrphans     = "orphans.md"
	ReportOutOfCorpus = "out-of-corpus.md"
	ReportUnresolved  = "refs-unresolved.md"
)

// Reports writes all four under reports/ and returns their names.
func (res *Result) Reports(root string) ([]string, error) {
	ix := res.Index
	files := []struct {
		name string
		body func(*Index) string
	}{
		{ReportMostCited, res.mostCited},
		{ReportOrphans, res.orphans},
		{ReportOutOfCorpus, res.outOfCorpus},
		{ReportUnresolved, res.unresolved},
	}
	var wrote []string
	for _, f := range files {
		path := filepath.Join(root, "reports", f.name)
		if err := os.WriteFile(path, []byte(tidy(f.body(ix))), 0o644); err != nil {
			return nil, err
		}
		wrote = append(wrote, filepath.Join("reports", f.name))
	}
	return wrote, nil
}

// StaleReports names the reports on disk that differ from what this run would
// write. They are committed, so they are checked in CI for the same reason the
// manifest is: a report a reader trusts has to be the one the corpus produces.
func (res *Result) StaleReports(root string) ([]string, error) {
	var stale []string
	for _, f := range []struct {
		name string
		body func(*Index) string
	}{
		{ReportMostCited, res.mostCited},
		{ReportOrphans, res.orphans},
		{ReportOutOfCorpus, res.outOfCorpus},
		{ReportUnresolved, res.unresolved},
	} {
		rel := filepath.Join("reports", f.name)
		got, err := os.ReadFile(filepath.Join(root, rel))
		if os.IsNotExist(err) {
			stale = append(stale, rel)
			continue
		}
		if err != nil {
			return nil, err
		}
		if string(got) != tidy(f.body(res.Index)) {
			stale = append(stale, rel)
		}
	}
	return stale, nil
}

// tidy is what every report goes out through. Each section ends by writing a
// blank line so the next one is separated from it, which leaves the last
// section of the file trailing one, and a file that ends in a blank line fails
// H05 along with everything else that is committed. Doing it here rather than
// in the four builders means the write and the staleness check cannot disagree.
func tidy(s string) string { return strings.TrimRight(s, "\n") + "\n" }

// header is the note every report opens with. It says the file is generated,
// because a reader who edits one by hand will lose the edit on the next run and
// should be told so before that happens rather than after.
func header(title, what string) string {
	return fmt.Sprintf("# %s\n\nGenerated by `bourbaki refs build`. %s\n\n", title, what)
}

// inDegree is how many references point at each statement, counted over the
// resolved edges. A reference that names a § and no statement in it is not a
// citation of any statement and is left out.
//
// So is a statement's reference to itself. Bourbaki sets the proof after the
// statement with nothing between them, so a proof that says "the properties of
// Proposition 7" is attributed to Proposition 7 and points at Proposition 7,
// and the resolver is right both times: that sentence is in that statement and
// it does name it. It is not the chapter leaning on the statement, which is
// what both reports that read this are about, and 76 of the 2122 edges are of
// that shape. Counting them put 25 statements in the most-cited table that
// nothing but their own proof mentions, and kept the same 25 out of the list of
// statements nothing cites, which is the number that would have been read as a
// claim about the corpus.
//
// Compared on the label rather than the tag, because an edge either side of an
// extraction and before the next tags merge has no tag yet, and two empty tags
// are not the same statement.
func (res *Result) inDegree() map[string]int {
	n := map[string]int{}
	for _, e := range res.Edges {
		if e.ToLabel != "" && e.ToLabel != e.FromLabel && e.How != BySection && e.How != OutOfCorpus {
			n[e.ToLabel]++
		}
	}
	return n
}

func (res *Result) mostCited(ix *Index) string {
	n := res.inDegree()
	type row struct {
		label string
		count int
	}
	var rows []row
	for label, c := range n {
		rows = append(rows, row{label, c})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].count != rows[j].count {
			return rows[i].count > rows[j].count
		}
		return rows[i].label < rows[j].label
	})

	var b strings.Builder
	b.WriteString(header("Most cited statements",
		"The statements the rest of the chapter leans on, by how many references point at them."))
	fmt.Fprintf(&b, "%d statements are cited at least once.\n\n", len(rows))
	b.WriteString("| references | tag | statement |\n|---:|---|---|\n")
	for i, r := range rows {
		if i >= 100 {
			fmt.Fprintf(&b, "\nThe remaining %d are cited %d times or fewer.\n",
				len(rows)-100, rows[99].count)
			break
		}
		fmt.Fprintf(&b, "| %d | %s | %s |\n", r.count, tagCell(ix, r.label), r.label)
	}
	return b.String()
}

func (res *Result) orphans(ix *Index) string {
	n := res.inDegree()
	var b strings.Builder
	b.WriteString(header("Statements nothing cites",
		"Statements no other statement in the chapter refers to. Most are the end of a line of reasoning rather than a fault, and the exercises are not counted, since the text almost never cites one."))

	total, orphan := 0, 0
	var bySection []string
	for i := range ix.Sections {
		s := &ix.Sections[i]
		var list []*Statement
		for _, st := range s.Statements {
			total++
			if n[st.Label] == 0 {
				orphan++
				list = append(list, st)
			}
		}
		if len(list) == 0 {
			continue
		}
		var sec strings.Builder
		fmt.Fprintf(&sec, "## %s\n\n%d of %d statements.\n\n| tag | statement |\n|---|---|\n",
			s.Label, len(list), len(s.Statements))
		for _, st := range list {
			fmt.Fprintf(&sec, "| %s | %s |\n", tagCell(ix, st.Label), st.Label)
		}
		bySection = append(bySection, sec.String())
	}
	fmt.Fprintf(&b, "%d of %d statements are cited by nothing, which is %.0f per cent.\n\n",
		orphan, total, pct(orphan, total))
	b.WriteString(strings.Join(bySection, "\n"))
	return b.String()
}

func (res *Result) outOfCorpus(*Index) string {
	type key struct{ book, chapter string }
	n := map[key]int{}
	for _, e := range res.Edges {
		if e.How == OutOfCorpus {
			n[key{e.Book, e.Chapter}]++
		}
	}
	type row struct {
		key   key
		count int
	}
	var rows []row
	byBook := map[string]int{}
	for k, c := range n {
		rows = append(rows, row{k, c})
		byBook[k.book] += c
	}
	// The chapter is the last word and not a nicety. The rows come out of a map,
	// so any two the rest of this cannot separate come out in whatever order the
	// map was walked in, and the file is committed and diffed in CI: a report
	// that reordered itself between two runs of the same build would fail the
	// check with nothing wrong. Most of the Books cite one or two chapters, so
	// the ties are the ordinary case here rather than the odd one.
	sort.Slice(rows, func(i, j int) bool {
		if byBook[rows[i].key.book] != byBook[rows[j].key.book] {
			return byBook[rows[i].key.book] > byBook[rows[j].key.book]
		}
		if rows[i].key.book != rows[j].key.book {
			return rows[i].key.book < rows[j].key.book
		}
		if rows[i].count != rows[j].count {
			return rows[i].count > rows[j].count
		}
		return chapterOrder(rows[i].key.chapter) < chapterOrder(rows[j].key.chapter)
	})

	var b strings.Builder
	b.WriteString(header("References that leave the corpus",
		"What chapter VIII cites that this corpus does not hold yet. It is the ingestion order, most cited first."))
	fmt.Fprintf(&b, "%d references point outside, over %d chapters of %d Books.\n\n",
		sum(byBook), len(rows), len(byBook))
	b.WriteString("| references | book | chapter |\n|---:|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %d | %s | %s |\n", r.count, r.key.book, r.key.chapter)
	}
	return b.String()
}

// chapterOrder sorts chapters the way the Éléments number them, so VIII comes
// after IV. A chapter this cannot read sorts last rather than failing: the
// report is a description and a citation with a malformed chapter should show
// in it, at the bottom, and not stop it being written.
func chapterOrder(s string) int {
	n, err := corpus.RomanOrder(s)
	if err != nil {
		return 1 << 30
	}
	return n
}

// unresolved is the one report that is an audit rather than a description. A
// reference the book makes to a statement the corpus does not hold is almost
// always a statement extraction ran into the paragraph above it, so this is
// read as a work list and not as a list of things the resolver got wrong.
func (res *Result) unresolved(*Index) string {
	byReason := map[string][]Problem{}
	for _, p := range res.Unresolved {
		byReason[p.Reason] = append(byReason[p.Reason], p)
	}
	reasons := make([]string, 0, len(byReason))
	for r := range byReason {
		reasons = append(reasons, r)
	}
	sort.Slice(reasons, func(i, j int) bool {
		if len(byReason[reasons[i]]) != len(byReason[reasons[j]]) {
			return len(byReason[reasons[i]]) > len(byReason[reasons[j]])
		}
		return reasons[i] < reasons[j]
	})

	var b strings.Builder
	b.WriteString(header("References that do not resolve",
		"Every citation the resolver could not follow, grouped by why. A group that names a statement of this chapter is a hole in the corpus and not a fault in the lookup."))
	total := len(res.Edges) + len(res.Unresolved)
	fmt.Fprintf(&b, "%d of %d references do not resolve, which is %.1f per cent.\n\n",
		len(res.Unresolved), total, pct(len(res.Unresolved), total))
	b.WriteString("| count | reason |\n|---:|---|\n")
	for _, r := range reasons {
		fmt.Fprintf(&b, "| %d | %s |\n", len(byReason[r]), r)
	}
	b.WriteString("\n")
	for _, r := range reasons {
		fmt.Fprintf(&b, "## %s\n\n", r)
		for _, p := range byReason[r] {
			fmt.Fprintf(&b, "- `%s:%d` %s\n", p.File, p.Line, quote(p.Raw))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// tagCell is the permanent tag of a statement, or a dash where one has not been
// assigned yet, which happens between an extraction and the next tags merge.
func tagCell(ix *Index, label string) string {
	if t := ix.Tag(label); t != "" {
		return t
	}
	return "-"
}

// quote puts a citation in backticks. The prose is full of pipes and asterisks
// and a table cell or a list item has to survive them.
func quote(s string) string {
	return "`" + strings.ReplaceAll(strings.TrimSpace(s), "`", "'") + "`"
}

func pct(n, of int) float64 {
	if of == 0 {
		return 0
	}
	return 100 * float64(n) / float64(of)
}

func sum(m map[string]int) int {
	n := 0
	for _, v := range m {
		n += v
	}
	return n
}
