package publish

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// withReports writes reports into the fixture's corpus, which is what the site
// reads them from. They are committed Markdown like everything else the site is
// built out of.
func withReports(t *testing.T, s *Site, files map[string]string) *Site {
	t.Helper()
	dir := filepath.Join(s.Root, "reports")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return s
}

// A report is a table of tags and the point of the table is to go and look at
// them, so every tag and every label the site holds is a link to its page.
func TestAReportLinksEveryTagAndLabelTheSiteHolds(t *testing.T) {
	s := withReports(t, testSite(t), map[string]string{"most-cited.md": strings.Join([]string{
		"# Most cited statements",
		"",
		"Generated by `bourbaki refs build`.",
		"",
		"| references | tag | statement |",
		"|---:|---|---|",
		"| 14 | 00GJ | alg-viii-s14-thm-1 |",
		"| 1 | 00H8 | alg-viii-s14-ex-8 |",
		"| 0 | 00ZZ | alg-viii-s99-thm-1 |",
		"",
	}, "\n")})

	got := s.mustPage(t, "reports/most-cited/index.html")
	for _, want := range []string{`<table class="report">`, `<th class="num">references</th>`, "<th>tag</th>"} {
		if !strings.Contains(got, want) {
			t.Errorf("the report page does not hold %q:\n%s", want, got)
		}
	}
	// The tag, and the label of the same statement, both reach the tag page.
	if !strings.Contains(got, `<a href="/tag/00GJ/">00GJ</a>`) ||
		!strings.Contains(got, `<a href="/tag/00GJ/">alg-viii-s14-thm-1</a>`) {
		t.Errorf("a statement in the corpus is not linked from the report:\n%s", got)
	}
	// An exercise is linked at its own page rather than at its tag page, which
	// is the canonical of the two.
	if !strings.Contains(got, `<a href="/en/alg/VIII/s14/ex/8/">alg-viii-s14-ex-8</a>`) {
		t.Errorf("an exercise in the corpus is not linked from the report:\n%s", got)
	}
	// And a tag the corpus does not hold is printed and not linked, since the
	// report is about the corpus as it is.
	if strings.Contains(got, ">00ZZ</a>") {
		t.Errorf("a tag with no page was linked:\n%s", got)
	}
	// The counts are right aligned, which is the only thing the alignment row of
	// the Markdown table is read for.
	if !strings.Contains(got, `<td class="num">14</td>`) {
		t.Errorf("the count column is not right aligned:\n%s", got)
	}
}

// The audit names a file and a line for every finding, and a finding whose
// place a reader cannot open is a finding nobody acts on.
func TestAReportLinksTheFilesItNames(t *testing.T) {
	s := withReports(t, testSite(t), map[string]string{"audit.md": strings.Join([]string{
		"# Corpus audit",
		"",
		"Generated by `bourbaki audit`. Do not edit.",
		"",
		"- **M04** every math span parses: not asked for",
		"- `content/en/alg/VIII/05_s5_commutation.md:420` two of one script against one base",
		"",
	}, "\n")})

	got := s.mustPage(t, "reports/audit/index.html")
	want := `<a href="https://github.com/tamnd/bourbaki/blob/main/content/en/alg/VIII/05_s5_commutation.md#L420">`
	if !strings.Contains(got, want) {
		t.Errorf("the report does not link the file it names:\n%s", got)
	}
	if !strings.Contains(got, "<li><strong>M04</strong> every math span parses: not asked for</li>") {
		t.Errorf("a bullet list came out as something else:\n%s", got)
	}
	// The command in the opening line is a command and not a path, so it is set
	// as code and linked at nothing.
	if !strings.Contains(got, "<code>bourbaki audit</code>. Do not edit.") {
		t.Errorf("a code span came out wrong:\n%s", got)
	}
}

// Every committed report is published, rather than a list of names written down
// in the code that somebody has to remember to add to.
func TestEveryCommittedReportIsPublishedAndListed(t *testing.T) {
	s := withReports(t, testSite(t), map[string]string{
		"orphans.md":    "# Statements nothing cites\n\nStatements no other statement refers to.\n",
		"printings.md":  "# The two printings against each other\n\nOne chapter printed twice is one chapter.\n",
		"audit.json":    `{"not":"markdown"}`,
		"ocr-usage.txt": "not markdown either",
	})
	dir := t.TempDir()
	wrote, err := s.Build(dir)
	if err != nil {
		t.Fatal(err)
	}
	have := map[string]bool{}
	for _, w := range wrote {
		have[w] = true
	}
	for _, want := range []string{"reports/index.html", "reports/orphans/index.html",
		"reports/printings/index.html"} {
		if !have[want] {
			t.Errorf("%s was not written", want)
		}
	}
	for _, not := range []string{"reports/audit.json/index.html", "reports/ocr-usage.txt/index.html"} {
		if have[not] {
			t.Errorf("%s was written, and it is not a report", not)
		}
	}
	// The index lists each one by its own heading and its own opening line, so
	// that a reader can tell which of them answers the question they have.
	index := s.mustPage(t, "reports/index.html")
	for _, want := range []string{
		`<a href="/reports/orphans/">Statements nothing cites</a>`,
		"Statements no other statement refers to.",
		`<a href="/reports/printings/">The two printings against each other</a>`,
	} {
		if !strings.Contains(index, want) {
			t.Errorf("the reports index does not hold %q:\n%s", want, index)
		}
	}
}

// A clone that has not run the tools has no reports directory, and the site is
// built from a clone.
func TestACorpusWithNoReportsStillBuilds(t *testing.T) {
	s := testSite(t)
	got := s.mustPage(t, "reports/index.html")
	if !strings.Contains(got, "This clone holds no report") {
		t.Errorf("the reports index does not say it is empty:\n%s", got)
	}
}

// The reports are generated by the tools out of the corpus, and the corpus is
// text out of a PDF. Neither is trusted markup.
func TestAReportCannotLeakMarkup(t *testing.T) {
	s := withReports(t, testSite(t), map[string]string{"orphans.md": strings.Join([]string{
		"# Statements nothing cites",
		"",
		"A paragraph naming <script>alert(1)</script> and a & in it.",
		"",
		"| tag | statement |",
		"|---|---|",
		"| 00GJ | <b>not bold</b> |",
		"",
	}, "\n")})

	got := s.mustPage(t, "reports/orphans/index.html")
	if strings.Contains(got, "<script>alert(1)</script>") || strings.Contains(got, "<b>not bold</b>") {
		t.Errorf("the report leaked markup:\n%s", got)
	}
	if !strings.Contains(got, "&lt;script&gt;") || !strings.Contains(got, "a &amp; in it") {
		t.Errorf("the report did not escape what it printed:\n%s", got)
	}
}
