package quality

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// The report is committed, and CI checks it by regenerating it and diffing. That
// one sentence decides its whole shape.
//
// Spec 08 §3 opens the file with a timestamp, a solver version and a corpus
// commit. None of the three can be here. A timestamp changes on every run, so
// the diff never comes back clean and the gate fires on every pull request
// regardless of the corpus. A version changes when the solver is tagged, which
// would turn every solver release into a red build on the content repository. A
// commit hash cannot be in a file that is part of the commit it names. What is
// left is a report that is a pure function of the corpus, which is what the rest
// of this package already is, and the run's own metadata goes to the JSON, where
// nothing diffs it.

// perCheck is how many findings a section of the report prints.
//
// M03 alone found 585 stranded characters and 38 wrong deltas on one chapter,
// and a report that printed all of them would be a thousand lines of the same
// sentence with nobody reading past the first screen. What is cut is always
// counted and always says how to see the rest, because a truncation that reads
// like completeness is worse than no report.
const perCheck = 25

// Report renders reports/audit.md.
func Report(r *Result) string {
	var b strings.Builder
	b.WriteString("# Corpus audit\n\n")
	b.WriteString("Generated by `bourbaki audit`. Do not edit.\n\n")
	b.WriteString("Every number here is a function of the committed Markdown and the manifests.\n")
	b.WriteString("There is no timestamp and no commit in it, so that CI can check this file by\n")
	b.WriteString("regenerating it and diffing.\n\n")
	b.WriteString(scope(r.Corpus) + "\n\n")

	b.WriteString("## Summary\n\n")
	b.WriteString("| Group | Hard | Soft | Not run | Failing |\n")
	b.WriteString("| --- | ---: | ---: | ---: | --- |\n")
	for _, g := range r.Groups() {
		failing := strings.Join(g.Failing, ", ")
		if failing == "" {
			failing = "none"
		}
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %s |\n", g.Group, g.Hard, g.Soft, g.NotRun, failing)
	}
	fmt.Fprintf(&b, "\n%d hard findings and %d soft, over %d rules that ran and %d that could not.\n",
		r.Hard(), r.Soft(), len(r.Outcomes)-len(r.Skipped()), len(r.Skipped()))
	if r.Hard() == 0 {
		b.WriteString("Every hard rule passes.\n")
	}

	if skipped := r.Skipped(); len(skipped) > 0 {
		b.WriteString("\n## Rules that did not run\n\n")
		b.WriteString("A rule that has nothing to look at is reported here rather than counted as a\n")
		b.WriteString("pass, because a green that comes from an empty corpus is the one kind nobody\n")
		b.WriteString("should trust.\n\n")
		for _, o := range skipped {
			fmt.Fprintf(&b, "- **%s** %s: %s\n", o.Check.ID, o.Check.Title, o.Skipped)
		}
	}

	for _, o := range r.Failing() {
		strength := "Soft"
		if o.Check.Hard {
			strength = "Hard"
		}
		fmt.Fprintf(&b, "\n## %s %s (%d)\n\n", o.Check.ID, o.Check.Title, len(o.Findings))
		fmt.Fprintf(&b, "%s, %s.\n\n", strength, o.Check.Group)
		for i, f := range o.Findings {
			if i == perCheck {
				fmt.Fprintf(&b, "\nand %d more, which `bourbaki audit -only %s` prints in full.\n",
					len(o.Findings)-perCheck, o.Check.ID)
				break
			}
			if at := f.At(); at != "" {
				fmt.Fprintf(&b, "- `%s` %s\n", at, f.Msg)
			} else {
				fmt.Fprintf(&b, "- %s\n", f.Msg)
			}
		}
	}
	return b.String()
}

// scope is the one line that says what was audited. Without it a report of forty
// passes says nothing: passing on an empty corpus and passing on the whole
// Éléments print the same table.
func scope(c *Corpus) string {
	var sections, exercises, solutions, translated int
	for _, d := range c.Docs {
		switch {
		case d.Kind == KindSolution:
			solutions++
		case d.Kind == KindExercise && d.Lang == "en":
			exercises++
		case d.Kind == KindSection && d.Lang == "en":
			sections++
		case d.Lang != "en":
			translated++
		}
	}
	chapters := map[string]bool{}
	for _, d := range c.Docs {
		if d.Lang == "en" && d.Section != nil {
			chapters[d.Section.Book+" "+d.Section.Chapter] = true
		}
	}
	var pages int
	for _, ps := range c.Pages {
		pages += len(ps)
	}
	tagged := len(c.Tags.Tags) + len(c.Tags.New)
	parts := []string{
		plural(len(chapters), "chapter", "chapters"),
		plural(sections, "section", "sections"),
		plural(exercises, "exercise", "exercises"),
		plural(pages, "extracted page", "extracted pages"),
		plural(tagged, "tag", "tags"),
	}
	if c.Refs != nil {
		parts = append(parts, plural(len(c.Refs.Edges), "reference", "references"))
	}
	if translated > 0 {
		parts = append(parts, plural(translated, "translated file", "translated files"))
	}
	if solutions > 0 {
		parts = append(parts, plural(solutions, "solution", "solutions"))
	}
	langs := c.Langs
	if len(langs) == 0 {
		langs = []string{"none"}
	}
	return fmt.Sprintf("Audited: %s. Languages: %s.",
		strings.Join(parts, ", "), strings.Join(langs, ", "))
}

func plural(n int, one, many string) string {
	if n == 1 {
		return fmt.Sprintf("%d %s", n, one)
	}
	return fmt.Sprintf("%d %s", n, many)
}

// JSONReport is the machine form, for the CI annotator and for anything that
// wants to track the numbers over time.
//
// This is where the run's own metadata belongs. Version and Commit change with
// every run and every release, which is exactly why they cannot be in the
// Markdown, and exactly why something reading a series of these runs wants them.
type JSONReport struct {
	Version  string         `json:"version,omitempty"`
	Commit   string         `json:"commit,omitempty"`
	Root     string         `json:"root"`
	Langs    []string       `json:"langs"`
	Hard     int            `json:"hard"`
	Soft     int            `json:"soft"`
	Checks   []JSONCheck    `json:"checks"`
	Findings []Finding      `json:"findings"`
	Counts   map[string]int `json:"counts"`
}

// JSONCheck is one rule's outcome without its findings, so that a consumer can
// tell a rule that passed from a rule that never ran. Those two are the same
// empty list and the difference is the whole point.
type JSONCheck struct {
	ID      string `json:"id"`
	Group   string `json:"group"`
	Hard    bool   `json:"hard"`
	Title   string `json:"title"`
	Skipped string `json:"skipped,omitempty"`
	Found   int    `json:"found"`
}

// JSON renders the machine form. version and commit are the run's, and are
// passed in rather than looked up here, because this package does not shell out.
func JSON(r *Result, version, commit string) ([]byte, error) {
	out := JSONReport{
		Version: version,
		Commit:  commit,
		Root:    r.Corpus.Root,
		Langs:   r.Corpus.Langs,
		Hard:    r.Hard(),
		Soft:    r.Soft(),
		Counts:  counts(r.Corpus),
	}
	for _, o := range r.Outcomes {
		out.Checks = append(out.Checks, JSONCheck{
			ID: o.Check.ID, Group: o.Check.Group, Hard: o.Check.Hard,
			Title: o.Check.Title, Skipped: o.Skipped, Found: len(o.Findings),
		})
	}
	out.Findings = r.Findings()
	if out.Findings == nil {
		out.Findings = []Finding{}
	}
	if out.Langs == nil {
		out.Langs = []string{}
	}
	return json.MarshalIndent(out, "", "  ")
}

// counts is the scope line as numbers.
func counts(c *Corpus) map[string]int {
	m := map[string]int{"tags": len(c.Tags.Tags) + len(c.Tags.New)}
	for _, d := range c.Docs {
		switch {
		case d.Kind == KindSolution:
			m["solutions"]++
		case d.Lang != "en":
			m["translated"]++
		case d.Kind == KindExercise:
			m["exercises"]++
		default:
			m["sections"]++
		}
	}
	for _, ps := range c.Pages {
		m["pages"] += len(ps)
	}
	if c.Refs != nil {
		m["references"] = len(c.Refs.Edges)
		m["unresolved"] = len(c.Refs.Unresolved)
	}
	return m
}

// Text is the terminal form: one line per finding, in the order the rules ran,
// which is the order somebody fixing them wants.
func Text(r *Result, verbose bool) string {
	var b strings.Builder
	for _, o := range r.Outcomes {
		if o.Skipped != "" {
			if verbose {
				fmt.Fprintf(&b, "%s  not run: %s\n", o.Check.ID, o.Skipped)
			}
			continue
		}
		if len(o.Findings) == 0 {
			if verbose {
				fmt.Fprintf(&b, "%s  ok  %s\n", o.Check.ID, o.Check.Title)
			}
			continue
		}
		for _, f := range o.Findings {
			b.WriteString(f.String() + "\n")
		}
	}
	return b.String()
}

// Failures is the one-line summary the command prints last, listing the hard
// rules that failed and nothing else, because that is the list somebody has to
// work through before the build goes green.
func Failures(r *Result) []string {
	var out []string
	for _, o := range r.Failing() {
		if o.Check.Hard {
			out = append(out, fmt.Sprintf("%s (%d)", o.Check.ID, len(o.Findings)))
		}
	}
	sort.Strings(out)
	return out
}
