package translate

import (
	"fmt"
	"strings"
	"testing"

	"github.com/tamnd/bourbaki-solver/glossary"
)

// The English used here is real: it is the opening of Corollary 1 to Theorem 1
// of Appendix 3 of chapter VIII, as the corpus holds it, and its Vietnamese is
// a translation of the same. Invented Markdown with $x$ in it would pass rules
// that real Bourbaki fails, which is how a rule comes to be written wrong.

const en = `#### Corollary 1 {#alg-viii-a3-thm-1-cor-1 .statement tag=00RV}

Let K be a commutative field, A be a commutative K-algebra generated by finitely many elements, and $\mathfrak{m}$ be a maximal ideal of A.

a) The degree of $A/\mathfrak{m}$ over K is finite.

The K-algebra $A/\mathfrak{m}$ is generated by finitely many elements, and $A/\mathfrak{m}$ is a field. By Theorem 1, the degree of $A/\mathfrak{m}$ is finite (V, §4, No. 1, p. 20, Theorem 1).`

const vi = `#### Hệ quả 1 {#alg-viii-a3-thm-1-cor-1 .statement tag=00RV}

Cho K là một trường giao hoán, A là một K-đại số giao hoán sinh bởi hữu hạn phần tử, và $\mathfrak{m}$ là một iđêan tối đại của A.

a) Bậc của $A/\mathfrak{m}$ trên K là hữu hạn.

K-đại số $A/\mathfrak{m}$ được sinh bởi hữu hạn phần tử, và $A/\mathfrak{m}$ là một trường. Theo Định lý 1, bậc của $A/\mathfrak{m}$ là hữu hạn (V, §4, No. 1, p. 20, Định lý 1).`

func rules(ps []Problem) []string {
	var out []string
	for _, p := range ps {
		out = append(out, p.Rule)
	}
	return out
}

func only(t *testing.T, ps []Problem, rule string) Problem {
	t.Helper()
	if len(ps) != 1 {
		t.Fatalf("wanted one problem, got %v: %v", rules(ps), ps)
	}
	if ps[0].Rule != rule {
		t.Fatalf("wanted rule %s, got %v", rule, ps[0])
	}
	return ps[0]
}

func TestAGoodTranslationIsAccepted(t *testing.T) {
	if ps := Audit("vi", en, vi); len(ps) != 0 {
		t.Fatalf("a correct translation was refused: %v", ps)
	}
}

func TestATidiedFormulaIsRefused(t *testing.T) {
	// The commonest quiet failure: the mathematics is still there, still says
	// the same thing, and is not the same bytes.
	bad := strings.Replace(vi, `$A/\mathfrak{m}$`, `$A / \mathfrak{m}$`, 1)
	p := only(t, Audit("vi", en, bad), RuleMath)
	if !strings.Contains(p.Msg, "math span 2") {
		t.Fatalf("did not name the span that changed: %v", p)
	}
}

func TestAFormulaTidiedLateStillShowsWhereItChanged(t *testing.T) {
	// A span of the inverse limits of chapter III opens with forty characters
	// two readings share, so a message cut from the front reads "the span is
	// x... and the English has x...", the same text twice. A chunk sat in the
	// queue for an hour being told that.
	want := `u_\beta \circ f_{\beta\alpha} = u_\alpha \circ g_{\alpha\beta}`
	got := strings.Replace(want, `g_{\alpha\beta}`, `g_{\alpha \beta}`, 1)
	mine, theirs := ShortDiff(got, want)
	if mine == theirs {
		t.Fatalf("the two halves of the message read alike: %s", mine)
	}
	if !strings.Contains(mine, `\\alpha \\beta`) || !strings.Contains(theirs, `\\alpha\\beta}`) {
		t.Fatalf("the window is not on the difference: %s and %s", mine, theirs)
	}
}

func TestAShortFormulaIsShownWhole(t *testing.T) {
	mine, theirs := ShortDiff(`x + y`, `x+y`)
	if mine != `"x + y"` || theirs != `"x+y"` {
		t.Fatalf("a short span was not shown whole: %s and %s", mine, theirs)
	}
}

func TestADroppedFormulaIsRefused(t *testing.T) {
	bad := strings.Replace(vi, ` và $A/\mathfrak{m}$ là một trường`, "", 1)
	ps := Audit("vi", en, bad)
	if len(ps) == 0 || ps[0].Rule != RuleMath {
		t.Fatalf("a dropped formula was not caught: %v", ps)
	}
	if !strings.Contains(ps[0].Msg, "has 4 math spans and the English has 5") {
		t.Fatalf("did not count the spans: %v", ps[0])
	}
}

func TestAChangedTagIsRefused(t *testing.T) {
	bad := strings.Replace(vi, "tag=00RV", "tag=00RW", 1)
	ps := Audit("vi", en, bad)
	if len(ps) != 2 {
		t.Fatalf("wanted the missing block and the invented one, got %v", ps)
	}
	for _, p := range ps {
		if p.Rule != RuleTag {
			t.Fatalf("wanted tag problems, got %v", p)
		}
	}
}

func TestARenumberedStatementIsRefused(t *testing.T) {
	// Hệ quả 2 where the English has Corollary 1. Everything that cites it
	// still says 1, and nothing else in the file has changed.
	bad := strings.Replace(vi, "#### Hệ quả 1 ", "#### Hệ quả 2 ", 1)
	p := only(t, Audit("vi", en, bad), RuleStructure)
	if !strings.Contains(p.Msg, "numbered 2") || !strings.Contains(p.Msg, "numbers it 1") {
		t.Fatalf("did not report both numbers: %v", p)
	}
}

func TestAHeadingThatChangedDepthIsRefused(t *testing.T) {
	bad := strings.Replace(vi, "#### Hệ quả", "### Hệ quả", 1)
	p := only(t, Audit("vi", en, bad), RuleStructure)
	if !strings.Contains(p.Msg, "level 3") {
		t.Fatalf("did not report the level: %v", p)
	}
}

func TestAnAnswerThatStopsEarlyIsRefused(t *testing.T) {
	bad := strings.Join(blocks(vi)[:2], "\n\n")
	// A truncated answer fails several rules at once, because a section that
	// stops early is short of formulae and short of citations as well as short
	// of blocks. This is the rule that says which of those it is.
	var said string
	for _, p := range Audit("vi", en, bad) {
		if p.Rule == RuleStructure {
			said = p.Msg
		}
	}
	if !strings.Contains(said, "has 2 blocks, the English has 4, and stops short of it") {
		t.Fatalf("did not say it was short: %q", said)
	}
}

// A bibliography entry is the name a library has the work under, so it stands
// as printed. The one below is entry 1 of the historical note of chapters I to
// IV, and the Vietnamese is what a run actually wrote for the note of chapter
// III, where nobody can look the book up any more.
func TestATranslatedBibliographyEntryIsRefused(t *testing.T) {
	bib := "1. O. Neugebauer, *Vorlesungen über die Geschichte der antiken " +
		"Mathematik*, Vol. I, Berlin (Springer), 1934."
	bad := "1. O. NEUGEBAUER, *Các bài giảng về lịch sử toán học cổ đại*, " +
		"tập I, Berlin (Springer), 1934."
	p := only(t, Audit("vi", bib, bad), RuleBibliography)
	if !strings.Contains(p.Msg, "bibliography entry 1") || !strings.Contains(p.Msg, "stands as printed") {
		t.Fatalf("did not say which entry, or why: %v", p)
	}
	if ps := Audit("vi", bib, bib); len(ps) != 0 {
		t.Fatalf("an entry copied as printed was refused: %v", ps)
	}
}

// The terminology rule read the titles of the 49 works chunk 30 of the note
// cites as seven terms left in English, and refused the chunk every time.
func TestTermsInsideABibliographyEntryAreNotTermsLeftInEnglish(t *testing.T) {
	g := &glossary.Glossary{Version: 3, Terms: []glossary.Term{
		{EN: "choice", VI: "lựa chọn"},
		{EN: "remark", VI: "chú ý"},
	}}
	bib := "43. K. GÖDEL, *The consistency of the axiom of choice*, Princeton, 1940.\n" +
		"45. M. ZORN, \"A remark on method in transfinite algebra\", **41** (1935)."
	if ps := AuditTerms("vi", g, bib, bib); len(ps) != 0 {
		t.Fatalf("the titles of two books were read as English left in: %v", ps)
	}
}

func TestAMisquotedReferenceIsRefused(t *testing.T) {
	// p. 20 became p. 26. This is the failure a reader cannot see and cannot
	// check without the English open beside them.
	bad := strings.Replace(vi, "p. 20", "p. 26", 1)
	ps := Audit("vi", en, bad)
	if len(ps) != 2 {
		t.Fatalf("wanted the missing citation and the invented one, got %v", ps)
	}
	if !strings.Contains(ps[0].Msg, "p.20") || !strings.Contains(ps[1].Msg, "p.26") {
		t.Fatalf("did not name the two pages: %v", ps)
	}
}

func TestSpacingInsideAReferenceIsNotAFailure(t *testing.T) {
	// "No.1" for "No. 1" is typesetting and not a citation.
	ok := strings.Replace(vi, "No. 1", "No.1", 1)
	if ps := Audit("vi", en, ok); len(ps) != 0 {
		t.Fatalf("tighter spacing in a reference was refused: %v", ps)
	}
}

func TestTheEnglishHandedBackIsRefused(t *testing.T) {
	p := only(t, Audit("vi", en, en), RuleLanguage)
	if !strings.Contains(p.Msg, "unchanged") {
		t.Fatalf("did not say what was wrong: %v", p)
	}
}

func TestCommentaryIsRefused(t *testing.T) {
	bad := "Here is the translation:\n\n" + vi
	ps := Audit("vi", en, bad)
	var found bool
	for _, p := range ps {
		if p.Rule == RuleCommentary {
			found = true
		}
	}
	if !found {
		t.Fatalf("a preamble got through: %v", ps)
	}
}

func TestAnInventedFrontMatterIsRefused(t *testing.T) {
	bad := "---\nlang: vi\nstatements: 1\n---\n\n" + vi
	ps := Audit("vi", en, bad)
	if len(ps) == 0 || ps[0].Rule != RuleFrontMatter {
		t.Fatalf("an invented head got through: %v", ps)
	}
}

func TestAnEmptyAnswerIsRefusedOnItsOwn(t *testing.T) {
	if ps := Audit("vi", en, "   \n\n"); len(ps) != 1 {
		t.Fatalf("wanted one problem for an empty answer, got %v", ps)
	}
}

func TestAnAnswerInTheWrongScriptIsRefused(t *testing.T) {
	// The Vietnamese, offered as the Japanese translation. It is not the
	// English, so the first language rule passes and the second is what
	// catches it.
	p := only(t, Audit("ja", en, vi), RuleLanguage)
	if !strings.Contains(p.Msg, "no ja writing") {
		t.Fatalf("did not name the language: %v", p)
	}
}

// A chunk of the appendix on the trace came back with two English sentences in
// the middle of it and Vietnamese on both sides, and every test above passed it
// because each asks about the whole chunk. The sentence here is the one that
// got through, put back where it stood.
func TestASentenceLeftInEnglishIsRefused(t *testing.T) {
	bad := strings.Replace(vi, "Theo Định lý 1,",
		"It therefore suffices to prove assertion b) when the A-module E is free. "+
			"There then exists a finitely generated free submodule F of E. Theo Định lý 1,", 1)
	p := only(t, Audit("vi", en, bad), RuleLanguage)
	if !strings.Contains(p.Msg, "nothing of vi") {
		t.Fatalf("did not say what was wrong: %v", p)
	}
	// It is the third language rule and not the second: the answer as a whole is
	// still written in Vietnamese, which is the point of the rule.
	if !glossary.WrittenIn("vi", bad) {
		t.Fatal("the answer does not read as Vietnamese, so the script rule would have caught it")
	}
}

// Both of these are real. gpt-5.4 wrote them into the Vietnamese introduction
// to Theory of Sets, one word each, inside sentences that are otherwise correct
// Vietnamese and that every other rule accepts.
func TestAWordInAnotherAlphabetIsRefused(t *testing.T) {
	for _, c := range []struct{ word, script string }{
		{"либо", "Cyrillic"},
		{"որևէ", "Armenian"},
	} {
		bad := strings.Replace(vi, "và", c.word, 1)
		p := only(t, Audit("vi", en, bad), RuleScript)
		if !strings.Contains(p.Msg, c.word) || !strings.Contains(p.Msg, c.script) {
			t.Errorf("did not name the word and its alphabet: %v", p)
		}
		if p.Line != 3 {
			t.Errorf("%s was reported on line %d", c.word, p.Line)
		}
	}
}

// The mathematics is full of Greek and it is not prose, so nothing in a formula
// is a word this rule has an opinion about.
func TestGreekInsideAFormulaIsNotAStrayAlphabet(t *testing.T) {
	src := strings.Replace(en, `$\mathfrak{m}$`, `$α$`, 1)
	tr := strings.Replace(vi, `$\mathfrak{m}$`, `$α$`, 1)
	if ps := Audit("vi", src, tr); len(ps) != 0 {
		t.Fatalf("a formula was read as prose: %v", ps)
	}
}

// A letter the English itself sets in prose is a letter the translation may
// keep. The book names Greek letters in words as well as in formulae, and a
// rule that refused those would refuse the only faithful answer.
func TestAnAlphabetTheEnglishUsesIsAllowed(t *testing.T) {
	src := strings.Replace(en, "a maximal ideal", "a maximal ideal, written σ,", 1)
	tr := strings.Replace(vi, "một iđêan tối đại", "một iđêan tối đại, viết là σ,", 1)
	if ps := Audit("vi", src, tr); len(ps) != 0 {
		t.Fatalf("a letter the source uses was refused: %v", ps)
	}
}

// Japanese is written in four alphabets and Vietnamese in one, and a rule that
// did not know that would refuse every Japanese section there is.
func TestJapaneseIsNotRefusedForBeingJapanese(t *testing.T) {
	ja := "#### 系 1 {#alg-viii-a3-thm-1-cor-1 .statement tag=00RV}\n\nカタカナと漢字とひらがな。"
	if ps := AuditScript("ja", en, ja); len(ps) != 0 {
		t.Fatalf("Japanese was refused: %v", ps)
	}
	if ps := AuditScript("vi", en, ja); len(ps) == 0 {
		t.Fatal("Japanese passed as Vietnamese")
	}
}

func TestEveryProblemIsReportedAndNotJustTheFirst(t *testing.T) {
	bad := strings.Replace(vi, "tag=00RV", "tag=00RW", 1)
	bad = strings.Replace(bad, "p. 20", "p. 26", 1)
	got := map[string]bool{}
	for _, p := range Audit("vi", en, bad) {
		got[p.Rule] = true
	}
	if !got[RuleTag] || !got[RuleReference] {
		t.Fatalf("wanted both a tag and a reference problem, got %v", got)
	}
}

func TestChunksNeverSplitABlock(t *testing.T) {
	body := strings.Repeat(en+"\n\n", 20)
	cs := Chunks(body)
	if len(cs) < 2 {
		t.Fatalf("wanted several chunks, got %d", len(cs))
	}
	var rejoined []string
	for i, c := range cs {
		if c.Index != i+1 || c.Of != len(cs) {
			t.Fatalf("chunk %d is numbered %d of %d", i, c.Index, c.Of)
		}
		rejoined = append(rejoined, c.Body)
	}
	if Join(rejoined) != Join([]string{body}) {
		t.Fatal("the chunks do not put the body back together")
	}
}

// The budget that matters is the mathematics. This body is well under
// ChunkChars and well over ChunkSpans, which is the case the appendix on the
// Nullstellensatz turned out to be and the case the character budget missed.
func TestAChunkCarriesOnlySoMuchMathematics(t *testing.T) {
	body := strings.TrimSpace(strings.Repeat("Let $x$ be in $A$ and $y$ in $B$.\n\n", 12))
	if len(body) > ChunkChars {
		t.Fatalf("the fixture is %d characters, so it does not test the span budget", len(body))
	}
	cs := Chunks(body)
	if len(cs) < 2 {
		t.Fatalf("a body with %d spans came out as one chunk", spanCount(body))
	}
	for _, c := range cs {
		if n := spanCount(c.Body); n > ChunkSpans {
			t.Errorf("chunk %d of %d carries %d spans, and the cap is %d",
				c.Index, c.Of, n, ChunkSpans)
		}
	}
	var rejoined []string
	for _, c := range cs {
		rejoined = append(rejoined, c.Body)
	}
	if Join(rejoined) != Join([]string{body}) {
		t.Fatal("splitting on the mathematics lost some of the body")
	}
}

// The footnotes of a note are 83 definitions with no blank line between them,
// which read as one block of 35,000 characters and went over as one question.
func TestARunOfFootnotesIsChunkedAndPutBackAsItWasWritten(t *testing.T) {
	var lines []string
	for i := 1; i <= 60; i++ {
		lines = append(lines, fmt.Sprintf("[^%d]: %s", i,
			strings.TrimSpace(strings.Repeat("a note on the text. ", 20))))
	}
	body := "The note itself.\n\n" + strings.Join(lines, "\n")
	cs := Chunks(body)
	if len(cs) < 2 {
		t.Fatalf("a run of %d footnotes came out as one chunk", len(lines))
	}
	var rejoined []string
	for _, c := range cs {
		if len(c.Body) > 2*ChunkChars {
			t.Errorf("chunk %d of %d is %d characters", c.Index, c.Of, len(c.Body))
		}
		rejoined = append(rejoined, c.Body)
	}
	got := Join(rejoined)
	if got != Join([]string{body}) {
		t.Fatal("the chunks do not put the note back together")
	}
	// One blank line, the one between the note and the first definition.
	if n := strings.Count(got, "\n\n[^"); n != 1 {
		t.Fatalf("%d definitions have a blank line above them, want 1", n)
	}
}

// A definition that runs on to a second line keeps it, and a definition that
// goes missing is caught.
func TestAFootnoteDefinitionIsABlockOfItsOwn(t *testing.T) {
	body := "[^1]: The first.\n    It runs on.\n[^2]: The second.\n[^3]: The third."
	if got := len(blocks(body)); got != 3 {
		t.Fatalf("the run came to %d blocks, want 3", got)
	}
	bad := "[^1]: Cái thứ nhất.\n    Nó chạy tiếp.\n[^2]: Cái thứ hai."
	p := only(t, Audit("vi", body, bad), RuleStructure)
	if !strings.Contains(p.Msg, "has 2 blocks, the English has 3") {
		t.Fatalf("a dropped definition was not counted: %v", p)
	}
}

// A single block over the cap still goes over, because a block is never split
// and half a paragraph is not a thing to ask anybody to translate.
func TestABlockOverTheSpanCapGoesOverOnItsOwn(t *testing.T) {
	heavy := strings.TrimSpace(strings.Repeat("$x$ and ", ChunkSpans+5))
	cs := Chunks("short block\n\n" + heavy)
	if len(cs) != 2 {
		t.Fatalf("wanted two chunks, got %d", len(cs))
	}
	if strings.TrimSpace(cs[1].Body) != heavy {
		t.Fatalf("the heavy block was cut: %q", cs[1].Body)
	}
}

func TestABlockLongerThanTheTargetGoesOverOnItsOwn(t *testing.T) {
	long := strings.Repeat("a ", ChunkChars)
	cs := Chunks("short block\n\n" + long)
	if len(cs) != 2 {
		t.Fatalf("wanted two chunks, got %d", len(cs))
	}
	if cs[0].Body != "short block" {
		t.Fatalf("the short block was not left alone: %q", cs[0].Body)
	}
}

func TestTheGlossaryBlockHoldsTheTermsThatAppear(t *testing.T) {
	g := &glossary.Glossary{Terms: []glossary.Term{
		{EN: "field", VI: "trường"},
		{EN: "maximal ideal", VI: "iđêan tối đại"},
		{EN: "quaternion", VI: "quaternion"},
	}}
	got := GlossaryBlock(g, "vi", en)
	if strings.Contains(got, "quaternion") {
		t.Fatalf("sent a term the section does not use:\n%s", got)
	}
	// Longest first, so the phrase is met before the word inside it.
	if !strings.HasPrefix(got, "maximal ideal | iđêan tối đại\nfield | trường\n") {
		t.Fatalf("wrong terms or wrong order:\n%s", got)
	}
}

func TestATermInsideAWordIsNotATerm(t *testing.T) {
	g := &glossary.Glossary{Terms: []glossary.Term{{EN: "ring", VI: "vành"}}}
	if got := GlossaryBlock(g, "vi", "The generating subset is not a ringlet."); got != "" {
		t.Fatalf("matched ring inside ringlet: %q", got)
	}
	if got := GlossaryBlock(g, "vi", "Let A be a ring."); got != "ring | vành\n" {
		t.Fatalf("did not match the word itself: %q", got)
	}
}

func TestATermWithNoRenderingIsNotSent(t *testing.T) {
	g := &glossary.Glossary{Terms: []glossary.Term{{EN: "field", ZH: "域"}}}
	if got := GlossaryBlock(g, "vi", en); got != "" {
		t.Fatalf("sent a row with no Vietnamese in it: %q", got)
	}
}

// The line of chapter I of Theory of Sets that this rule was written for. The
// words inside the formula are prose, and an answer that copies them through
// with the symbols has left part of the section in English.
const enProse = en + "\n\nThe relation $((\\text{not } A) \\text{ or } B)$ holds for every A."

func TestWordsLeftInEnglishInsideAFormulaAreRefused(t *testing.T) {
	bad := vi + "\n\nHệ thức $((\\text{not } A) \\text{ or } B)$ đúng với mọi A."
	ps := Audit("vi", enProse, bad)
	if len(ps) != 2 {
		t.Fatalf("wanted both runs reported, got %v: %v", rules(ps), ps)
	}
	for _, p := range ps {
		if p.Rule != RuleMathProse {
			t.Fatalf("wanted rule %s, got %v", RuleMathProse, p)
		}
		if !strings.Contains(p.Msg, "math span 6") {
			t.Fatalf("did not name the span: %v", p)
		}
	}
}

func TestWordsTranslatedInsideAFormulaAreAccepted(t *testing.T) {
	good := vi + "\n\nHệ thức $((\\text{không } A) \\text{ hoặc } B)$ đúng với mọi A."
	if ps := Audit("vi", enProse, good); len(ps) != 0 {
		t.Fatalf("a translated formula was refused: %v", ps)
	}
}

// The symbols are still compared, words in the span or not.
func TestASymbolThatMovedInsideAFormulaWithWordsIsStillRefused(t *testing.T) {
	bad := vi + "\n\nHệ thức $((\\text{không } A) \\text{ hoặc } C)$ đúng với mọi A."
	p := only(t, Audit("vi", enProse, bad), RuleMath)
	if !strings.Contains(p.Msg, "math span 6") {
		t.Fatalf("did not name the span that changed: %v", p)
	}
}

// A passage written entirely in symbols translates to itself, and the language
// rule has to let it.
//
// Bourbaki writes whole blocks with no prose in them. One chunk of exercise 8 of
// the appendix to chapter I is three displays of the tables for not and or, and
// one chunk of chapter II, § 2 is a single containment. Every model hands those
// back as they stand, because that is the right answer, and the run refused
// them, asked twice more, killed the chunk and refused the section. Both files
// were held out of the corpus by it.
func TestAPassageOfPureMathematicsMayComeBackUnchanged(t *testing.T) {
	for _, c := range []struct {
		name string
		body string
	}{
		{"three displays and nothing else",
			"$$\\neg 0 = 1, \\qquad \\neg 1 = 0,$$\n$$\\vee 11 = 1, \\qquad \\vee 12 = 2.$$"},
		{"one containment", "$$A' \\times B' \\subset A \\times B.$$"},
		{"a display written between fences", "$$\n(C'|y)(B|x)A\n$$"},
		{"a part's name and its formula", "(a) $x \\in A$"},
	} {
		if got := Audit("vi", c.body, c.body); len(got) > 0 {
			t.Errorf("%s: Audit refused an answer identical to a passage with no prose in it: %v", c.name, got)
		}
	}
}

// And a passage that does have prose is still refused when it comes back in
// English, which is the whole point of the rule.
func TestAPassageWithProseMayNot(t *testing.T) {
	for _, c := range []struct {
		name string
		body string
	}{
		{"a sentence around the mathematics", "Let $A$ be a set and let $B$ be another one."},
		{"a heading over a display", "#### Lemma 2 {#ens-ii-lem-2 .statement tag=00LC}\n\n$$A \\subset B.$$"},
	} {
		got := Audit("vi", c.body, c.body)
		if len(got) == 0 {
			t.Errorf("%s: Audit accepted the English back unchanged", c.name)
			continue
		}
		if got[0].Rule != RuleLanguage {
			t.Errorf("%s: first complaint is %s, want %s", c.name, got[0].Rule, RuleLanguage)
		}
	}
}
