package pagemap

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Dir is where page maps live inside a corpus checkout.
func Dir(root string) string { return filepath.Join(root, "manifests", "page-map") }

// Path is the map for one volume. It is a TSV rather than YAML because it has
// one row per PDF page, around 1700 rows across the three volumes, and a TSV
// diffs line by line when a reading changes.
func Path(root, book string) string { return filepath.Join(Dir(root), book+".tsv") }

// GapsPath is the audit companion: coverage, the gaps and the conflicts.
func GapsPath(root, book string) string {
	return filepath.Join(Dir(root), book+"-gaps.json")
}

const tsvHeader = "pdf_page\tchapter\tpage\tconfidence"

// Save writes the map and its gap report under root.
func (m *Map) Save(root string) error {
	if err := os.MkdirAll(Dir(root), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by bourbaki pagemap build. Do not edit.\n")
	prefix := ""
	if m.Prefix != "" {
		prefix = " prefix=" + m.Prefix
	}
	first := ""
	if m.FirstPage != 0 {
		first = " first_page=" + strconv.Itoa(m.FirstPage)
	}
	restarts := ""
	if len(m.Restarts) > 0 {
		var pages []string
		for _, r := range m.Restarts {
			pages = append(pages, strconv.Itoa(r))
		}
		restarts = " restarts=" + strings.Join(pages, ",")
	}
	transposed := ""
	if len(m.Transposed) > 0 {
		var swaps []string
		for _, s := range m.Transposed {
			swaps = append(swaps, fmt.Sprintf("%d-%d", s[0], s[1]))
		}
		transposed = " transposed=" + strings.Join(swaps, ",")
	}
	fmt.Fprintf(&b, "# book=%s grammar=%s pagination=%s%s%s%s%s pdf_pages=%d\n",
		m.Book, m.Grammar, m.Pagination, prefix, first, restarts, transposed, m.PDFPages)
	fmt.Fprintln(&b, tsvHeader)
	for _, e := range m.Entries {
		page := ""
		if e.Page > 0 {
			page = strconv.Itoa(e.Page)
		}
		fmt.Fprintf(&b, "%d\t%s\t%s\t%s\n", e.PDFPage, e.Chapter, page, e.Confidence)
	}
	if err := os.WriteFile(Path(root, m.Book), []byte(b.String()), 0o644); err != nil {
		return err
	}
	rep, err := json.MarshalIndent(m.Report(), "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(GapsPath(root, m.Book), append(rep, '\n'), 0o644)
}

// Report is the published audit of one map.
type Report struct {
	Book        string         `json:"book"`
	Grammar     Grammar        `json:"grammar"`
	Pagination  Pagination     `json:"pagination"`
	Prefix      string         `json:"prefix,omitempty"`
	FirstPage   int            `json:"first_page,omitempty"`
	Restarts    []int          `json:"restarts,omitempty"`
	Transposed  [][2]int       `json:"transposed,omitempty"`
	PDFPages    int            `json:"pdf_pages"`
	BodyPages   int            `json:"body_pages"`
	FrontMatter int            `json:"front_matter_pages"`
	Counts      map[string]int `json:"counts"`
	PrintedPct  float64        `json:"printed_pct_of_body"`
	Chapters    []Span         `json:"chapters"`
	Steps       []Step         `json:"steps"`
	Conflicts   []Conflict     `json:"conflicts"`
	Gaps        []Gap          `json:"gaps"`
}

// Report builds the audit record. Conflicts and gaps are published in full: a
// map that quietly drops the readings it could not reconcile is a map nobody
// can check.
func (m *Map) Report() Report {
	counts := map[string]int{}
	printed := 0
	for c, n := range m.Counts() {
		counts[string(c)] = n
		if c.Printed() {
			printed += n
		}
	}
	body := m.BodyPages()
	r := Report{
		Book: m.Book, Grammar: m.Grammar, Pagination: m.Pagination,
		Prefix:    m.Prefix,
		FirstPage: m.FirstPage, Restarts: m.Restarts, Transposed: m.Transposed,
		PDFPages: m.PDFPages, BodyPages: body, FrontMatter: m.PDFPages - body,
		Counts: counts, Chapters: m.Chapters, Steps: m.Steps,
		Conflicts: m.Conflicts, Gaps: m.Gaps,
	}
	if body > 0 {
		r.PrintedPct = float64(printed) / float64(body) * 100
	}
	if r.Steps == nil {
		r.Steps = []Step{}
	}
	if r.Conflicts == nil {
		r.Conflicts = []Conflict{}
	}
	if r.Gaps == nil {
		r.Gaps = []Gap{}
	}
	return r
}

// Load reads a map back from a corpus checkout.
func Load(root, book string) (*Map, error) {
	f, err := os.Open(Path(root, book))
	if err != nil {
		return nil, err
	}
	defer f.Close()

	m := &Map{Book: book}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "#") {
			for _, kv := range strings.Fields(strings.TrimPrefix(line, "#")) {
				k, v, ok := strings.Cut(kv, "=")
				if !ok {
					continue
				}
				switch k {
				case "grammar":
					m.Grammar = Grammar(v)
				case "pagination":
					m.Pagination = Pagination(v)
				case "prefix":
					m.Prefix = v
				case "first_page":
					if m.FirstPage, err = strconv.Atoi(v); err != nil {
						return nil, fmt.Errorf("%s: bad first_page in %q", Path(root, book), line)
					}
				case "restarts":
					for _, p := range strings.Split(v, ",") {
						n, err := strconv.Atoi(p)
						if err != nil {
							return nil, fmt.Errorf("%s: bad restarts in %q", Path(root, book), line)
						}
						m.Restarts = append(m.Restarts, n)
					}
				case "transposed":
					for _, s := range strings.Split(v, ",") {
						a, b, ok := strings.Cut(s, "-")
						if !ok {
							return nil, fmt.Errorf("%s: bad transposed in %q", Path(root, book), line)
						}
						first, err := strconv.Atoi(a)
						if err != nil {
							return nil, fmt.Errorf("%s: bad transposed in %q", Path(root, book), line)
						}
						second, err := strconv.Atoi(b)
						if err != nil {
							return nil, fmt.Errorf("%s: bad transposed in %q", Path(root, book), line)
						}
						m.Transposed = append(m.Transposed, [2]int{first, second})
					}
				}
			}
			continue
		}
		if line == tsvHeader || strings.TrimSpace(line) == "" {
			continue
		}
		f := strings.Split(line, "\t")
		if len(f) != 4 {
			return nil, fmt.Errorf("%s: want 4 columns, got %d in %q", Path(root, book), len(f), line)
		}
		n, err := strconv.Atoi(f[0])
		if err != nil {
			return nil, fmt.Errorf("%s: bad pdf_page in %q", Path(root, book), line)
		}
		e := Entry{PDFPage: n, Chapter: f[1], Confidence: Confidence(f[3])}
		if f[2] != "" {
			if e.Page, err = strconv.Atoi(f[2]); err != nil {
				return nil, fmt.Errorf("%s: bad page in %q", Path(root, book), line)
			}
		}
		m.Entries = append(m.Entries, e)
	}
	// The TSV holds one row per page and nothing else, because that is what
	// diffs well. The chapter spans are a fact about those rows rather than a
	// second source of truth, so they are worked out again on the way back in.
	m.PDFPages = len(m.Entries)
	m.Chapters = spansFor(m.Entries, chaptersOf(m.Entries))

	if err := sc.Err(); err != nil {
		return nil, err
	}
	m.PDFPages = len(m.Entries)
	m.Gaps = findGaps(m.Entries)
	order, err := printingOrder(len(m.Entries), m.Transposed)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", Path(root, book), err)
	}
	m.Steps = stepsOf(m.Entries, order)
	return m, nil
}

// stepsOf recovers the steps from the rows, the way the chapter spans and the
// gaps are recovered.
//
// Without this a loaded map has no steps at all, and Validate reads the two
// leaves chapter VIII does not print as two unexplained jumps and the chapter
// itself as 490 printed pages over 488 with nothing to account for the
// difference. That is three problems reported against a map that is correct,
// which is worse than no check: it is a check that teaches people to ignore it.
//
// A step is not a second source of truth here. The rows already say where the
// printed number jumps, so this reads it off them rather than trusting anything
// the builder wrote down and a later hand edit could have left behind.
func stepsOf(entries []Entry, order []int) []Step {
	var out []Step
	for i := 1; i < len(order); i++ {
		prev, cur := entries[order[i-1]-1], entries[order[i]-1]
		if prev.Page == 0 || cur.Page == 0 || prev.Chapter != cur.Chapter {
			continue
		}
		if cur.Page <= prev.Page+1 {
			continue
		}
		s := Step{AtPDFPage: cur.PDFPage, Chapter: cur.Chapter,
			FromOffset: prev.PDFPage - prev.Page, ToOffset: cur.PDFPage - cur.Page}
		for p := prev.Page + 1; p < cur.Page; p++ {
			s.MissingPages = append(s.MissingPages, p)
		}
		out = append(out, s)
	}
	return out
}

// chaptersOf lists the chapters the entries mention, in the order they appear,
// which is the order the volume prints them.
func chaptersOf(entries []Entry) []string {
	var out []string
	seen := map[string]bool{}
	for _, e := range entries {
		if e.Chapter == "" || seen[e.Chapter] {
			continue
		}
		seen[e.Chapter] = true
		out = append(out, e.Chapter)
	}
	return out
}
