package pagemap

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

func TestSaveLoadRoundTrip(t *testing.T) {
	root := t.TempDir()
	m, err := Build(perChapterVolume(), Options{Book: "mini", Chapters: []string{"IV"}})
	if err != nil {
		t.Fatal(err)
	}
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}

	back, err := Load(root, "mini")
	if err != nil {
		t.Fatal(err)
	}
	if back.Grammar != m.Grammar || back.Pagination != m.Pagination {
		t.Errorf("header did not survive: %s %s", back.Grammar, back.Pagination)
	}
	if len(back.Entries) != len(m.Entries) {
		t.Fatalf("got %d entries, want %d", len(back.Entries), len(m.Entries))
	}
	for i := range m.Entries {
		a, b := m.Entries[i], back.Entries[i]
		if a.PDFPage != b.PDFPage || a.Chapter != b.Chapter || a.Page != b.Page || a.Confidence != b.Confidence {
			t.Errorf("entry %d: %+v != %+v", i, a, b)
		}
	}
}

func TestSaveWritesTheGapReport(t *testing.T) {
	root := t.TempDir()
	m, err := Build(perChapterVolume(), Options{Book: "mini", Chapters: []string{"IV"}})
	if err != nil {
		t.Fatal(err)
	}
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(GapsPath(root, "mini"))
	if err != nil {
		t.Fatal(err)
	}
	var r Report
	if err := json.Unmarshal(b, &r); err != nil {
		t.Fatal(err)
	}
	if r.BodyPages != 11 || r.FrontMatter != 2 {
		t.Errorf("body %d, front matter %d; want 11 and 2", r.BodyPages, r.FrontMatter)
	}
	if len(r.Steps) != 1 || len(r.Conflicts) != 1 {
		t.Errorf("steps %d, conflicts %d; want 1 and 1", len(r.Steps), len(r.Conflicts))
	}
	// The gaps are the runs the map worked out rather than read: the chapter
	// opener, the section opener, the overruled misread, and the front matter.
	if len(r.Gaps) != 4 {
		t.Errorf("gaps = %+v, want 4 runs", r.Gaps)
	}
}

func TestSaveWritesAGeneratedHeader(t *testing.T) {
	root := t.TempDir()
	m, err := Build(perChapterVolume(), Options{Book: "mini", Chapters: []string{"IV"}})
	if err != nil {
		t.Fatal(err)
	}
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(Path(root, "mini"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# Generated by bourbaki pagemap build") {
		t.Errorf("the map should say it is generated, got %q", string(b[:40]))
	}
}

func TestLoadRejectsABadRow(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(Dir(root), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(Path(root, "mini"), []byte(tsvHeader+"\n1\tIV\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Load(root, "mini"); err == nil {
		t.Error("a row with the wrong number of columns should be an error")
	}
}

// The validator reads the map back off disk as well as building it, so what the
// volume said about where its scan begins has to survive the header.
func TestTheHeaderCarriesWhereTheScanBegins(t *testing.T) {
	root := t.TempDir()
	m, err := Build(perChapterVolume(), Options{Book: "mini", Chapters: []string{"IV"}, FirstPage: 3})
	if err != nil {
		t.Fatal(err)
	}
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(Path(root, "mini"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "first_page=3") {
		t.Errorf("the header does not say where the scan begins:\n%s", strings.SplitN(string(b), "\n", 3)[1])
	}
	back, err := Load(root, "mini")
	if err != nil {
		t.Fatal(err)
	}
	if back.FirstPage != 3 {
		t.Errorf("first page came back as %d, want 3", back.FirstPage)
	}
	// A volume whose scan starts at the beginning writes nothing.
	plain, err := Build(perChapterVolume(), Options{Book: "plain", Chapters: []string{"IV"}})
	if err != nil {
		t.Fatal(err)
	}
	if err := plain.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err = os.ReadFile(Path(root, "plain"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), "first_page") {
		t.Error("a scan that starts at the beginning wrote a first page anyway")
	}
}

// The restarts have to survive the round trip for the same reason the first
// page does: Validate runs against a map loaded from disk, and without them the
// one place the numbering is allowed to go backwards reads as the fit slipping.
func TestTheHeaderCarriesWhereTheNumberingStartsOver(t *testing.T) {
	root := t.TempDir()
	m, err := Build(perChapterVolume(), Options{Book: "mini", Chapters: []string{"IV"},
		Restarts: []int{3, 5}})
	if err != nil {
		t.Fatal(err)
	}
	if err := m.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(Path(root, "mini"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "restarts=3,5") {
		t.Errorf("the header does not say where the numbering starts over:\n%s",
			strings.SplitN(string(b), "\n", 3)[1])
	}
	back, err := Load(root, "mini")
	if err != nil {
		t.Fatal(err)
	}
	if len(back.Restarts) != 2 || back.Restarts[0] != 3 || back.Restarts[1] != 5 {
		t.Errorf("the restarts came back as %v, want [3 5]", back.Restarts)
	}
	// A volume that numbers itself once through writes nothing.
	plain, err := Build(perChapterVolume(), Options{Book: "plain", Chapters: []string{"IV"}})
	if err != nil {
		t.Fatal(err)
	}
	if err := plain.Save(root); err != nil {
		t.Fatal(err)
	}
	b, err = os.ReadFile(Path(root, "plain"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), "restarts") {
		t.Error("a volume numbered once through wrote a restart anyway")
	}
}
